# Welcome to Jekyll!
#


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: amesones-dev blog
description: >- # this means to ignore newlines until "baseurl:"

 A collection of Google Cloud / DevOps / Python / Flask tools, guides and apps
baseurl: "/blog" # the sub-path of your site, e.g. /blog
url: "https://amesones-dev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  amesones-dev
linkedin_username: amesones-devops
permalink: /:categories/:year/:month/:day/:title


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
