title: GCP DevOps blog
author:
  name: Antonio Mesones
  email: amesones@live.co.uk
description: >- # this means to ignore newlines until "baseurl:"

 A collection of Google Cloud / DevOps / Python / Flask tools, guides and apps
baseurl: "/blog" # the sub-path of your site, e.g. /blog
url: "https://amesones-dev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  amesones-dev
linkedin_username: amesones-devops



# Build settings
markdown: GFM
remote_theme: minima
minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/amesones-dev" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/devops-amesones" }

plugins:
 - jekyll-paginate

paginate: 7
# Relative to baseurl
paginate_path: "/posts/page:num/"


